declare const classNames: {
  readonly workerData: "workerData";
  readonly workerInitial: "workerInitial";
  readonly avatarWrapper: "avatarWrapper";
  readonly editIcon: "editIcon";
  readonly small: "small";
  readonly workerAvatar: "workerAvatar";
  readonly large: "large";
  readonly workerName: "workerName";
  readonly workerMail: "workerMail";
  readonly workerDataTitle: "workerDataTitle";
  readonly workerInformation: "workerInformation";
  readonly editableField: "editableField";
  readonly "react-datepicker-wrapper": "react-datepicker-wrapper";
  readonly workerLogin: "workerLogin";
  readonly workerFirstName: "workerFirstName";
  readonly workerMiddleName: "workerMiddleName";
  readonly workerLastName: "workerLastName";
  readonly workerBirthday: "workerBirthday";
  readonly workerNumber: "workerNumber";
  readonly workerStartdate: "workerStartdate";
  readonly workerPosition: "workerPosition";
};
export = classNames;
