declare const classNames: {
  readonly modalOverlay: "modalOverlay";
  readonly modalContent: "modalContent";
  readonly closeButton: "closeButton";
  readonly form: "form";
  readonly addAchievePhotoContainer: "addAchievePhotoContainer";
  readonly iconAddAchieve: "iconAddAchieve";
  readonly titleHeadIcon: "titleHeadIcon";
  readonly descriptionHeadIcon: "descriptionHeadIcon";
  readonly iconAddPhoto: "iconAddPhoto";
  readonly formGroupName: "formGroupName";
  readonly formGroupDescription: "formGroupDescription";
  readonly formGroupRank: "formGroupRank";
  readonly formGroupImage: "formGroupImage";
  readonly inputContainer: "inputContainer";
  readonly formGroupBackground: "formGroupBackground";
  readonly fileDownloadImage: "fileDownloadImage";
  readonly labelFileDownload: "labelFileDownload";
  readonly formGroup: "formGroup";
  readonly titleInput: "titleInput";
  readonly rankInput: "rankInput";
  readonly fileDownload: "fileDownload";
  readonly inputContainer_ButtonAddBackground: "inputContainer_ButtonAddBackground";
  readonly formActions: "formActions";
  readonly cancelButton: "cancelButton";
  readonly submitButton: "submitButton";
};
export = classNames;
