declare const classNames: {
  readonly workerModalAddUser: "workerModalAddUser";
  readonly title: "title";
  readonly formFilling__rightContent: "formFilling__rightContent";
  readonly WorkersModalAddUserContent: "WorkersModalAddUserContent";
  readonly header: "header";
  readonly avatarUser: "avatarUser";
  readonly workerLoginAdd: "workerLoginAdd";
  readonly description__title: "description__title";
  readonly workersModalAddUser__input: "workersModalAddUser__input";
  readonly formFilling: "formFilling";
  readonly btnAddTag: "btnAddTag";
  readonly checkbox__link: "checkbox__link";
  readonly workerBirthdayAdd: "workerBirthdayAdd";
  readonly workerNameAdd: "workerNameAdd";
  readonly workerSecondNameAdd: "workerSecondNameAdd";
  readonly workerPatronymiAdd: "workerPatronymiAdd";
  readonly workerPhone: "workerPhone";
  readonly workerPassword: "workerPassword";
  readonly workerPositionAdd: "workerPositionAdd";
  readonly workerEmailAdd: "workerEmailAdd";
  readonly workerStartdateAdd: "workerStartdateAdd";
  readonly btnGroups: "btnGroups";
  readonly btn__close: "btn__close";
  readonly btn__add: "btn__add";
  readonly errorMessages: "errorMessages";
};
export = classNames;
